{dms}: {
  pkgs,
  lib,
  config,
  ...
}: let
  root = ./..;

  cfg = config.programs.meowtugen;
  configHome = config.xdg.configHome;

  sineModEntry = pkgs.writeText "meowtugen-sine-entry.json" (builtins.toJSON {
    meowtugen = {
      id = "meowtugen";
      name = "meowtugen";
      description = "Live-reloads chrome/meowtugen.css generated by matugen.";
      version = "1.0.0";
      style = {chrome = "userChrome.css";};
      scripts = {"meowtugen.uc.js" = {include = ["chrome://browser/content/browser.xhtml"];};};
      origin = "store";
      enabled = true;
      no-updates = true;
    };
  });

  withSineMod = cfg.zen.enable && cfg.zen.withSine;
  zenCssFile =
    if cfg.zen.withSine
    then "meowtugen.css"
    else "userChrome.css";
in {
  options.programs.meowtugen = {
    enable = lib.mkEnableOption "meowtugen matugen templates";

    autoEnable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to enable all meowtugen app templates by default. Set to false to opt in per app instead.";
    };

    package = lib.mkPackageOption pkgs "matugen" {};

    discord = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = cfg.autoEnable;
        defaultText = lib.literalExpression "config.programs.meowtugen.autoEnable";
        description = "Whether to enable the Discord client template.";
      };

      configPath = lib.mkOption {
        type = lib.types.str;
        default = "${configHome}/equibop";
        description = "Discord client config folder path.";
      };
    };

    zed.enable = lib.mkOption {
      type = lib.types.bool;
      default = cfg.autoEnable;
      defaultText = lib.literalExpression "config.programs.meowtugen.autoEnable";
      description = "Whether to enable the Zed editor template.";
    };

    zen = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = cfg.autoEnable;
        defaultText = lib.literalExpression "config.programs.meowtugen.autoEnable";
        description = "Whether to enable the Zen browser template.";
      };

      profiles = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = ["default"];
        description = "Zen browser profiles the template is rendered into (and, with withSine, where the Sine mod is installed).";
      };

      withSine = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Write the Zen template to chrome/meowtugen.css and manage the Sine hot-reload mod.";
      };
    };

    foot.enable = lib.mkOption {
      type = lib.types.bool;
      default = cfg.autoEnable;
      defaultText = lib.literalExpression "config.programs.meowtugen.autoEnable";
      description = "Whether to enable the foot terminal template.";
    };

    niri.enable = lib.mkOption {
      type = lib.types.bool;
      default = cfg.autoEnable;
      defaultText = lib.literalExpression "config.programs.meowtugen.autoEnable";
      description = "Whether to enable the niri wm template.";
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      home.packages = [cfg.package];

      xdg.configFile."matugen/config.toml".source = (pkgs.formats.toml {}).generate "config.toml" {
        config = {};

        templates = let
          dmsTemplates = "${dms}/quickshell/matugen/templates";

          discordSplashMerge = pkgs.writeShellScript "meowtugen-discord-splash-merge" ''
            set -eu

            SETTINGS="${cfg.discord.configPath}/settings.json"
            FRAGMENT="${cfg.discord.configPath}/splash-colors.json"

            if [ ! -f "$SETTINGS" ]; then
              echo "meowtugen: $SETTINGS not found, skipping splash merge"
              exit 0
            fi

            TMP="$(mktemp "$SETTINGS.tmp.XXXXXX")"
            trap 'rm -f "$TMP"' EXIT

            ${lib.getExe pkgs.jq} -s '.[0] * .[1]' "$SETTINGS" "$FRAGMENT" > "$TMP"
            ${lib.getExe pkgs.jq} empty "$TMP"

            mv "$TMP" "$SETTINGS"
            trap - EXIT
          '';
        in
          lib.optionalAttrs cfg.discord.enable {
            discord = {
              input_path = "${dmsTemplates}/vesktop.css";
              output_path = "${cfg.discord.configPath}/themes/meowtugen.css";
            };

            discord_splash = {
              input_path = "${root}/templates/discord-splash.json";
              output_path = "${cfg.discord.configPath}/splash-colors.json";
              post_hook = "${discordSplashMerge}";
            };
          }
          // lib.optionalAttrs cfg.zed.enable {
            zed = {
              input_path = "${root}/templates/zed.json";
              output_path = "${configHome}/zed/themes/meowtugen.json";
            };
          }
          // lib.optionalAttrs cfg.zen.enable (lib.listToAttrs (map (profile: {
              name = "zen-${profile}";
              value = {
                input_path = "${root}/templates/zen.css";
                output_path = "${configHome}/zen/${profile}/chrome/${zenCssFile}";
              };
            })
            cfg.zen.profiles))
          // lib.optionalAttrs cfg.foot.enable {
            foot_colors.input_path = "${root}/templates/foot/colors.ini";

            foot_reload = {
              input_path = "${root}/templates/foot/reload.sh";
              output_path = "${configHome}/foot/reload.sh";
              post_hook = "sh ${configHome}/foot/reload.sh";
            };

            foot = {
              input_path = "${root}/templates/foot/foot.ini";
              output_path = "${configHome}/foot/colors.ini";
            };
          }
          // lib.optionalAttrs cfg.niri.enable {
            niri = {
              input_path = "${dmsTemplates}/niri-colors.kdl";
              output_path = "${configHome}/niri/colors.kdl";
            };
          };
      };
    }
    {
      xdg.configFile = lib.mkIf withSineMod (lib.listToAttrs (lib.concatMap (profile: [
          {
            name = "zen/${profile}/chrome/sine-mods/meowtugen/userChrome.css";
            value.source = "${root}/sine-mod/userChrome.css";
          }
          {
            name = "zen/${profile}/chrome/sine-mods/meowtugen/meowtugen.uc.js";
            value.source = "${root}/sine-mod/meowtugen.uc.js";
          }
        ])
        cfg.zen.profiles));

      home.activation.meowtugenSineMod = lib.mkIf withSineMod (lib.hm.dag.entryAfter ["writeBoundary"] ''
        for PROFILE in ${lib.concatStringsSep " " cfg.zen.profiles}; do
          MODS_FILE="${configHome}/zen/$PROFILE/chrome/sine-mods/mods.json"

          if [ -f "$MODS_FILE" ]; then
            $DRY_RUN_CMD ${lib.getExe pkgs.jq} -s '.[0] * .[1]' "$MODS_FILE" ${sineModEntry} > "$MODS_FILE.tmp" \
              && $DRY_RUN_CMD ${lib.getExe pkgs.jq} empty "$MODS_FILE.tmp" \
              && $DRY_RUN_CMD mv "$MODS_FILE.tmp" "$MODS_FILE" \
              && $VERBOSE_ECHO "meowtugen: registered sine mod in $MODS_FILE"
          else
            $DRY_RUN_CMD mkdir -p "$(dirname "$MODS_FILE")" \
              && $DRY_RUN_CMD cp ${sineModEntry} "$MODS_FILE" \
              && $VERBOSE_ECHO "meowtugen: created $MODS_FILE with sine mod entry"
          fi
        done
      '');
    }
  ]);
}
